[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#0A0D11"
foreground = "#E6EBF1"
bright_foreground = "#FFFFFF"

[colors.cursor]
cursor = "#A4C6E8"
text = "#0A0D11"

[colors.selection]
background = "#1B222C"
text = "#E6EBF1"

[colors.normal]
black   = "#0A0D11"
red     = "#E46D75"
green   = "#A6D782"
yellow  = "#E5BE6C"
blue    = "#9ACFFF"
magenta = "#C9A6EB"
cyan    = "#8ED3E6"
white   = "#E6EBF1"

[colors.bright]
black   = "#4B545F"
red     = "#E17376"
green   = "#A4E4B5"
yellow  = "#F5CA7A"
blue    = "#80B0FF"
magenta = "#C9A6EB"
cyan    = "#93D7E8"
white   = "#FFFFFF"
