local colors = {
    bg               = "NONE",
    fg               = "#DDE3EA",
    cursorline       = "#1A1F26",
    selection        = "#2A333E",
    linenr           = "#5C6670",
    cursorlnr        = "#B8DCE5",
    statuslinebg     = "#0E1116",
    statuslinefg     = "#A0AAB5",
    pmenu            = "#1E252E",
    comment          = "#6E7A85",
    keyword          = "#B58CEB",
    string           = "#A6D47E",
    func             = "#E2BF76",
    type             = "#80BFFF",
    constant         = "#F2A77E",
    number           = "#FFAE74",
    operator         = "#8AD8F0",
    variable         = "#DDE3EA",
    error            = "#E06C75",
    warning          = "#E5B76C",
    info             = "#82B0FF",
    hint             = "#9FE8B1",
    searchBg         = "#3A5A80",
    searchFg         = "#FFFFFF",
    curSearch        = "#5EA0FF",
    fzfMatch         = "#FFD666",
    boldFunction     = true,
    italicKeyword    = true,
    constBuiltinBold = true,
    operatorBold     = false,
    methodItalic     = true,
    keywordBold      = false,
}

return colors
